module.exports = {
  extends: [
    'eslint:recommended',
    'plugin:react/recommended',
    'react-app',
    'plugin:jsx-a11y/recommended',
    'prettier',
    'prettier/react',
  ],
  parser: 'babel-eslint',
  plugins: ['jsx-a11y'],
  rules: {
    'dot-notation': 'error',
    'func-style': ['error', 'declaration', { allowArrowFunctions: true }],
    'id-length': 'error',
    'new-cap': 'error',
    'no-alert': 'error',
    'no-sync': 'error',
    'no-unneeded-ternary': 'error',
    'no-var': 'error',
    'object-shorthand': 'error',
    'operator-assignment': 'error',
    'prefer-spread': 'error',
    radix: 'error',
    'require-await': 'warn',
    yoda: 'error',
  },
};
